version: '2'

services:
  nginx:
    restart: always
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./project/app:/app:Z
      - ./project/log:/var/log/nginx:Z
      - ./project/etc/nginx.conf:/etc/nginx/nginx.conf:Z
